In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [ ]:
LABELS_FILEPATH = "./data/MSL+SMAP/labeled_anomalies.csv"
TRAINSET_FILEPATH = "./data/MSL+SMAP/data/train"
TESTSET_FILEPATH = "./data/MSL+SMAP/data/test"

labels = pd.read_csv(LABELS_FILEPATH)
labels.info()
labels.head(100)

<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   chan_id            82 non-null     str
 1   spacecraft         82 non-null     str
 2   anomaly_sequences  82 non-null     str
 3   class              82 non-null     str
 4   num_values         82 non-null     int64
dtypes: int64(1), str(4)
memory usage: 6.2 KB

,chan_id,spacecraft,anomaly_sequences,class,num_values
0,P-1,SMAP,"[[2149, 2349], [4536, 4844], [3539, 3779]]","[contextual, contextual, contextual]",8505
1,S-1,SMAP,"[[5300, 5747]]",[point],7331
2,E-1,SMAP,"[[5000, 5030], [5610, 6086]]","[contextual, contextual]",8516
3,E-2,SMAP,"[[5598, 6995]]",[point],8532
4,E-3,SMAP,"[[5094, 8306]]",[point],8307
...,...,...,...,...,...
77,P-11,MSL,"[[1778, 1898], [1238, 1344]]","[point, point]",3535
78,D-15,MSL,"[[1500, 2140]]",[point],2158
79,D-16,MSL,"[[600, 1250]]",[contextual],2191
80,M-7,MSL,"[[940, 1040]]",[point],2156
81,F-8,MSL,"[[1950, 2486]]",[contextual],2487

In [10]:
trainset = np.load(TRAINSET_FILEPATH+'/P-1.npy')
print(trainset.shape)
testset = np.load(TESTSET_FILEPATH+'/P-1.npy')
print(testset.shape)

(2872, 25)
(8505, 25)

In [ ]:
swatAttackFilepath = "./data/SWaT/attack.csv"
swatMergedFilepath = "./data/SWaT/merged.csv"
swatNormalFilepath = "./data/SWaT/normal.csv"

labels = pd.read_csv(swatNormalFilepath)
labels.info()
labels.head(50)

<class 'pandas.DataFrame'>
RangeIndex: 1387098 entries, 0 to 1387097
Data columns (total 53 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0    Timestamp     1387098 non-null  str
 1   FIT101         1387098 non-null  float64
 2   LIT101         1387098 non-null  float64
 3    MV101         395298 non-null   float64
 4   P101           1387098 non-null  int64
 5   P102           1387098 non-null  int64
 6    AIT201        395298 non-null   float64
 7   AIT202         1387098 non-null  float64
 8   AIT203         1387098 non-null  float64
 9   FIT201         1387098 non-null  float64
 10   MV201         395298 non-null   float64
 11   P201          395298 non-null   float64
 12   P202          395298 non-null   float64
 13  P203           1387098 non-null  int64
 14   P204          395298 non-null   float64
 15  P205           1387098 non-null  int64
 16  P206           1387098 non-null  int64
 17  DPIT301        1387098 non-null  float64
 18  FIT301         1387098 non-null  float64
 19  LIT301         1387098 non-null  float64
 20  MV301          1387098 non-null  int64
 21  MV302          1387098 non-null  int64
 22   MV303         395298 non-null   float64
 23  MV304          1387098 non-null  int64
 24  P301           1387098 non-null  int64
 25  P302           1387098 non-null  int64
 26  AIT401         1387098 non-null  float64
 27  AIT402         1387098 non-null  float64
 28  FIT401         1387098 non-null  float64
 29  LIT401         1387098 non-null  float64
 30  P401           1387098 non-null  int64
 31  P402           1387098 non-null  int64
 32  P403           1387098 non-null  int64
 33  P404           1387098 non-null  int64
 34  UV401          1387098 non-null  int64
 35  AIT501         1387098 non-null  float64
 36  AIT502         1387098 non-null  float64
 37  AIT503         1387098 non-null  float64
 38  AIT504         1387098 non-null  float64
 39  FIT501         1387098 non-null  float64
 40  FIT502         1387098 non-null  float64
 41  FIT503         1387098 non-null  float64
 42  FIT504         1387098 non-null  float64
 43  P501           1387098 non-null  int64
 44  P502           1387098 non-null  int64
 45  PIT501         1387098 non-null  float64
 46  PIT502         1387098 non-null  float64
 47  PIT503         1387098 non-null  float64
 48  FIT601         1387098 non-null  float64
 49  P601           1387098 non-null  int64
 50  P602           1387098 non-null  int64
 51  P603           1387098 non-null  int64
 52  Normal/Attack  1387098 non-null  str
dtypes: float64(31), int64(20), str(2)
memory usage: 598.0 MB

,Timestamp,FIT101,LIT101,MV101,P101,P102,AIT201,AIT202,AIT203,FIT201,...,P501,P502,PIT501,PIT502,PIT503,FIT601,P601,P602,P603,Normal/Attack
0,28/12/2015 10:00:00 AM,2.427057,522.8467,2.0,2,1,262.0161,8.396437,328.6337,2.445391,...,2,1,250.8652,1.649953,189.5988,0.000128,1,1,1,Normal
1,28/12/2015 10:00:01 AM,2.446274,522.8860,2.0,2,1,262.0161,8.396437,328.6337,2.445391,...,2,1,250.8652,1.649953,189.6789,0.000128,1,1,1,Normal
2,28/12/2015 10:00:02 AM,2.489191,522.8467,2.0,2,1,262.0161,8.394514,328.6337,2.442316,...,2,1,250.8812,1.649953,189.6789,0.000128,1,1,1,Normal
3,28/12/2015 10:00:03 AM,2.534350,522.9645,2.0,2,1,262.0161,8.394514,328.6337,2.442316,...,2,1,250.8812,1.649953,189.6148,0.000128,1,1,1,Normal
4,28/12/2015 10:00:04 AM,2.569260,523.4748,2.0,2,1,262.0161,8.394514,328.6337,2.443085,...,2,1,250.8812,1.649953,189.5027,0.000128,1,1,1,Normal
5,28/12/2015 10:00:05 AM,2.609294,523.8673,2.0,2,1,262.0161,8.394514,328.6337,2.444110,...,2,1,250.7530,1.649953,189.5027,0.000128,1,1,1,Normal
6,28/12/2015 10:00:06 AM,2.637158,524.1028,2.0,2,1,262.0161,8.394514,328.6337,2.444110,...,2,1,250.5928,1.649953,189.5027,0.000128,1,1,1,Normal
7,28/12/2015 10:00:07 AM,2.652211,524.2206,2.0,2,1,262.0161,8.394514,328.6337,2.441803,...,2,1,250.5928,1.649953,189.5027,0.000128,1,1,1,Normal
8,28/12/2015 10:00:08 AM,2.655735,524.4954,2.0,2,1,262.0161,8.394514,328.6337,2.441803,...,2,1,250.9132,1.649953,189.5027,0.000128,1,1,1,Normal
9,28/12/2015 10:00:09 AM,2.649970,524.0636,2.0,2,1,262.0161,8.394514,328.6337,2.441803,...,2,1,250.9132,1.649953,189.5668,0.000128,1,1,1,Normal
10,28/12/2015 10:00:10 AM,2.630433,524.1028,2.0,2,1,262.0161,8.394514,328.6337,2.441803,...,2,1,251.1055,1.649953,189.8231,0.000128,1,1,1,Normal
11,28/12/2015 10:00:11 AM,2.621785,523.7496,2.0,2,1,262.0161,8.391951,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128,1,1,1,Normal
12,28/12/2015 10:00:12 AM,2.616020,523.4355,2.0,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128,1,1,1,Normal
13,28/12/2015 10:00:13 AM,2.599366,523.0430,2.0,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128,1,1,1,Normal
14,28/12/2015 10:00:14 AM,2.588476,522.7290,2.0,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128,1,1,1,Normal
15,28/12/2015 10:00:15 AM,2.567979,522.6505,2.0,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128,1,1,1,Normal
16,28/12/2015 10:00:16 AM,2.556769,522.6897,2.0,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
17,28/12/2015 10:00:17 AM,2.534350,522.6897,2.0,2,1,262.0161,8.390669,328.6081,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
18,28/12/2015 10:00:18 AM,2.521859,522.6505,2.0,2,1,262.0161,8.390669,328.3773,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
19,28/12/2015 10:00:19 AM,2.502642,522.6897,2.0,2,1,262.0161,8.390669,328.3773,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
20,28/12/2015 10:00:20 AM,2.489191,522.7290,2.0,2,1,262.0161,8.390669,328.3773,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
21,28/12/2015 10:00:21 AM,2.473497,522.5327,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
22,28/12/2015 10:00:22 AM,2.458764,522.8860,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
23,28/12/2015 10:00:23 AM,2.444031,523.4355,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
24,28/12/2015 10:00:24 AM,2.434744,523.6710,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
25,28/12/2015 10:00:25 AM,2.423854,523.7496,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
26,28/12/2015 10:00:26 AM,2.421932,523.8281,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128,1,1,1,Normal
27,28/12/2015 10:00:27 AM,2.425776,524.2598,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1535,1.649953,189.8872,0.000128,1,1,1,Normal
28,28/12/2015 10:00:28 AM,2.471575,524.1421,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.0414,1.649953,189.8872,0.000128,1,1,1,Normal
29,28/12/2015 10:00:29 AM,2.527624,524.2598,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.0414,1.649953,189.8872,0.000128,1,1,1,Normal
30,28/12/2015 10:00:30 AM,2.554847,524.6523,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.0414,1.649953,189.8071,0.000128,1,1,1,Normal
31,28/12/2015 10:00:31 AM,2.598725,524.3383,2.0,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.0414,1.649953,189.8071,0.000128,1,1,1,Normal
32,28/12/2015 10:00:32 AM,2.639721,524.5346,2.0,2,1,262.0161,8.390669,328.4799,2.439881,...,2,1,251.0414,1.649953,189.8071,0.000128,1,1,1,Normal
33,28/12/2015 10:00:33 AM,2.667585,524.2991,2.0,2,1,262.0161,8.392271,328.4030,2.439881,...,2,1,250.9453,1.649953,189.5988,0.000128,1,1,1,Normal
34,28/12/2015 10:00:34 AM,2.673029,524.2991,2.0,2,1,262.0161,8.392271,328.4030,2.439881,...,2,1,250.8171,1.649953,189.5988,0.000128,1,1,1,Normal
35,28/12/2015 10:00:35 AM,2.653172,524.2206,2.0,2,1,262.0161,8.392271,328.4030,2.439881,...,2,1,250.7049,1.649953,189.5828,0.000128,1,1,1,Normal
36,28/12/2015 10:00:36 AM,2.629152,524.4561,2.0,2,1,262.0161,8.392271,328.4030,2.439881,...,2,1,250.7049,1.649953,189.4546,0.000128,1,1,1,Normal
37,28/12/2015 10:00:37 AM,2.622105,524.4561,2.0,2,1,262.0161,8.392271,328.4030,2.439881,...,2,1,250.7049,1.649953,189.4546,0.000128,1,1,1,Normal
38,28/12/2015 10:00:38 AM,2.619543,524.8486,2.0,2,1,262.0161,8.392271,328.4030,2.439881,...,2,1,250.7049,1.649953,189.4226,0.000128,1,1,1,Normal
39,28/12/2015 10:00:39 AM,2.606412,525.3982,2.0,2,1,262.0161,8.392271,328.4030,2.439881,...,2,1,250.7049,1.649953,189.3425,0.000128,1,1,1,Normal
40,28/12/2015 10:00:40 AM,2.589117,525.3196,2.0,2,1,262.0161,8.392271,328.4030,2.439881,...,2,1,250.6569,1.649953,189.3425,0.000128,1,1,1,Normal
41,28/12/2015 10:00:41 AM,2.574704,525.5159,2.0,2,1,262.0161,8.391310,328.4030,2.439881,...,2,1,250.5447,1.649953,189.3425,0.000128,1,1,1,Normal
42,28/12/2015 10:00:42 AM,2.556129,525.6729,2.0,2,1,262.0161,8.389067,328.4030,2.439881,...,2,1,250.5447,1.649953,189.3425,0.000128,1,1,1,Normal
43,28/12/2015 10:00:43 AM,2.545559,525.9084,2.0,2,1,262.0161,8.389067,328.4030,2.437318,...,2,1,250.5447,1.649953,189.3425,0.000128,1,1,1,Normal
44,28/12/2015 10:00:44 AM,2.524741,525.7907,2.0,2,1,262.0161,8.389067,328.4030,2.437318,...,2,1,250.5447,1.649953,189.3745,0.000128,1,1,1,Normal
45,28/12/2015 10:00:45 AM,2.512891,525.9084,2.0,2,1,262.0161,8.389067,328.4030,2.437318,...,2,1,250.5447,1.649953,189.3745,0.000128,1,1,1,Normal
46,28/12/2015 10:00:46 AM,2.495276,525.7122,2.0,2,1,262.0161,8.389067,328.4286,2.439240,...,2,1,250.7210,1.649953,189.5347,0.000128,1,1,1,Normal
47,28/12/2015 10:00:47 AM,2.480863,525.5944,2.0,2,1,262.0161,8.389067,328.5312,2.440393,...,2,1,250.8331,1.649953,189.5347,0.000128,1,1,1,Normal
48,28/12/2015 10:00:48 AM,2.460366,525.3196,2.0,2,1,262.0161,8.389067,328.5312,2.440393,...,2,1,250.8812,1.649953,189.5347,0.000128,1,1,1,Normal
49,28/12/2015 10:00:49 AM,2.448195,525.3982,2.0,2,1,262.0161,8.389067,328.5312,2.440393,...,2,1,250.9132,1.649953,189.6629,0.000128,1,1,1,Normal